### ISSUE TITLE
C3 preview, black bar on top

### ISSUE THREAD

**Issue by MikalDev** [ElectronForConstruct/template#15]
Black bar appears on top of e4c preview. Note that other browser elements cover it (InputText box and Browser style buttons. It also covers Steam Overlay at the top. This black bar does not appear on a built Electron app.

![](https://cdn.discordapp.com/attachments/245307898958184449/544396953996230656/unknown.png)

### System
- C3, built GW 1.42
- MacOS 10.14
- Windows 10

**Comment by Armaldio** [comment]
Can you replace `preload.js` in your project with this one: https://raw.githubusercontent.com/ElectronForConstruct/template/master/template/preload.js and confim me it's fixed ?

**Comment by gcstudio** [comment]
Bellow can be found the new preload.js in action while testing the c3 preview, but the element construct-devtool is disabled as i seen.

What line would enable the construct-devtool in the preload.js?


![c3-preview-e4c-disabled-construct-devtool](https://user-images.githubusercontent.com/7048869/53663647-f53d1180-3c6e-11e9-9575-612a4f8601b9.jpg)

**Comment by Armaldio** [comment]
Here are the developer settings available to put inside your `config.js` file
![image](https://user-images.githubusercontent.com/3089715/53665892-ae352900-3c3a-11e9-9310-4f6ca2d65e93.png)

**Comment by Armaldio** [comment]
Can be closed ? @MikalDev @gcstudio

**Comment by MikalDev** [comment]
It looks like you got it figured out, ok to close on my side.
